# Generated by Django 4.1.3 on 2022-11-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_remove_watchlist_movie_watchlist_movie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movies",
            old_name="title",
            new_name="movie",
        ),
    ]
