# Generated by Django 4.1.3 on 2022-11-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0007_rename_title_movies_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="movie",
            field=models.ManyToManyField(related_name="movielist", to="movies.movies"),
        ),
    ]
